let
  FilePath = Excel.CurrentWorkbook(){[Name = "FilePathFolder"]}[Content]{0}[Column1], 
  FileName = Excel.CurrentWorkbook(){[Name = "FileName"]}[Content]{0}[Column1], 
  Source = Excel.Workbook(File.Contents(FilePath & FileName), null), 
  RTAD310_Sheet = Source{[Item = "RTAD310", Kind = "Sheet"]}[Data], 
  #"Clean & Promote Headers" = 
    let
      firstN = Table.FirstN(RTAD310_Sheet, 1), 
      renames = List.Transform(
        Table.ColumnNames(RTAD310_Sheet), 
        each {
          _, 
          Text.Combine(
            List.Transform(
              Table.Column(firstN, _), 
              each Text.Trim(Text.Replace(Text.From(_), "#(lf)", " "))
            ), 
            ""
          )
        }
      ), 
      renamedTable = Table.RenameColumns(RTAD310_Sheet, renames)
    in
      Table.Skip(renamedTable, 1), 
  #"Split Column by Delimiter" = Table.SplitColumn(
    #"Clean & Promote Headers", 
    "Program Name", 
    Splitter.SplitTextByEachDelimiter({" - "}, QuoteStyle.Csv, false), 
    {"Client", "Program Name.2"}
  ), 
  #"Separate Eff & Exp dates" = Table.SplitColumn(
    #"Split Column by Delimiter", 
    "Experience Period", 
    Splitter.SplitTextByEachDelimiter({"-"}, QuoteStyle.Csv, false), 
    {"Effective", "Expiration"}
  ), 
  #"Trimmed Text" = Table.TransformColumns(
    Table.TransformColumnTypes(
      #"Separate Eff & Exp dates", 
      {
        {"Avg Wkly Wage", type text}, 
        {"Clmt Age", type text}, 
        {"Juris Days Lost", type text}, 
        {"Total Recov", type text}, 
        {"Legacy Recov", type text}, 
        {"Non-Legal Recov", type text}, 
        {"Legal Recov", type text}, 
        {"Med/BI Recov", type text}, 
        {"Ind/PD Recov", type text}, 
        {"Total Inc (Gross)", type text}, 
        {"Total Outsd", type text}, 
        {"Total PTD", type text}, 
        {"Non- Legal Inc", type text}, 
        {"Non- Legal Outsd", type text}, 
        {"Non- Legal PTD", type text}, 
        {"Legal Inc", type text}, 
        {"Legal Outsd", type text}, 
        {"Legal PTD", type text}, 
        {"Med/BI Inc", type text}, 
        {"Med/BI Outsd", type text}, 
        {"Med/BI PTD", type text}, 
        {"Ind/PD Inc", type text}, 
        {"Ind/PD Outsd", type text}, 
        {"Ind/PD PTD", type text}, 
        {"Loss Date", type text}
      }, 
      "en-US"
    ), 
    {
      {"Insurer  Cat Cd", Text.Trim, type text}, 
      {"MCO Number", Text.Trim, type text}, 
      {"Cat Code", Text.Trim, type text}, 
      {"Geo Region Code", Text.Trim, type text}, 
      {"Claims Made Date", Text.Trim, type text}, 
      {"CP Term Date", Text.Trim, type text}, 
      {"Client Program Status", Text.Trim, type text}, 
      {"Insured  Driver Last Name", Text.Trim, type text}, 
      {"Avg Wkly Wage", Text.Trim, type text}, 
      {"Clmt Job Code", Text.Trim, type text}, 
      {"Clmt Empl No", Text.Trim, type text}, 
      {"Clmt Sex", Text.Trim, type text}, 
      {"Clmt Age", Text.Trim, type text}, 
      {"Juris Days Lost", Text.Trim, type text}, 
      {"Policy Number", Text.Trim, type text}, 
      {"Fed/State Clm No", Text.Trim, type text}, 
      {"Client Clm No", Text.Trim, type text}, 
      {"Adjuster", Text.Trim, type text}, 
      {"Expiration", Text.Trim, type text}, 
      {"Effective", Text.Trim, type text}, 
      {"NCCI Inj Desc", Text.Trim, type text}, 
      {"NCCI Inj Code", Text.Trim, type text}, 
      {"NCCI Class Code", Text.Trim, type text}, 
      {"Location Description", Text.Trim, type text}, 
      {"Location Code", Text.Trim, type text}, 
      {"Level 7 Name", Text.Trim, type text}, 
      {"Level 7 Code", Text.Trim, type text}, 
      {"Level 6 Name", Text.Trim, type text}, 
      {"Level 6 Code", Text.Trim, type text}, 
      {"Level 5 Name", Text.Trim, type text}, 
      {"Level 5 Code", Text.Trim, type text}, 
      {"Level 4 Name", Text.Trim, type text}, 
      {"Level 4 Code", Text.Trim, type text}, 
      {"Level 3 Name", Text.Trim, type text}, 
      {"Level 3 Code", Text.Trim, type text}, 
      {"Level 2 Name", Text.Trim, type text}, 
      {"Level 2 Code", Text.Trim, type text}, 
      {"Recision Date", Text.Trim, type text}, 
      {"Denial Date", Text.Trim, type text}, 
      {"Controverted", Text.Trim, type text}, 
      {"Body Part", Text.Trim, type text}, 
      {"Injury Desc", Text.Trim, type text}, 
      {"Cause Description", Text.Trim, type text}, 
      {"Total Recov", Text.Trim, type text}, 
      {"Legacy Recov", Text.Trim, type text}, 
      {"Non-Legal Recov", Text.Trim, type text}, 
      {"Legal Recov", Text.Trim, type text}, 
      {"Med/BI Recov", Text.Trim, type text}, 
      {"Ind/PD Recov", Text.Trim, type text}, 
      {"Total Inc (Gross)", Text.Trim, type text}, 
      {"Total Outsd", Text.Trim, type text}, 
      {"Total PTD", Text.Trim, type text}, 
      {"Non- Legal Inc", Text.Trim, type text}, 
      {"Non- Legal Outsd", Text.Trim, type text}, 
      {"Non- Legal PTD", Text.Trim, type text}, 
      {"Legal Inc", Text.Trim, type text}, 
      {"Legal Outsd", Text.Trim, type text}, 
      {"Legal PTD", Text.Trim, type text}, 
      {"Med/BI Inc", Text.Trim, type text}, 
      {"Med/BI Outsd", Text.Trim, type text}, 
      {"Med/BI PTD", Text.Trim, type text}, 
      {"Ind/PD Inc", Text.Trim, type text}, 
      {"Ind/PD Outsd", Text.Trim, type text}, 
      {"Ind/PD PTD", Text.Trim, type text}, 
      {"Minor Coverage Description", Text.Trim, type text}, 
      {"Minor Cov Cd", Text.Trim, type text}, 
      {"LOB Code", Text.Trim, type text}, 
      {"Litigation Ind", Text.Trim, type text}, 
      {"Privacy Claim", Text.Trim, type text}, 
      {"Closed/ Reopened Date", Text.Trim, type text}, 
      {"Claim Status Description", Text.Trim, type text}, 
      {"Claim Status Code", Text.Trim, type text}, 
      {"Reported Date", Text.Trim, type text}, 
      {"Loss Date", Text.Trim, type text}, 
      {"Occupation", Text.Trim, type text}, 
      {"Claimant Name", Text.Trim, type text}, 
      {"Premium State", Text.Trim, type text}, 
      {"Garage State", Text.Trim, type text}, 
      {"Benefit State", Text.Trim, type text}, 
      {"Loss State", Text.Trim, type text}, 
      {"Insurer Code", Text.Trim, type text}, 
      {"S/I", Text.Trim, type text}, 
      {"Insurer Name", Text.Trim, type text}, 
      {"Claim Number", Text.Trim, type text}, 
      {"Occurrence Number", Text.Trim, type text}, 
      {"Claim Office", Text.Trim, type text}, 
      {"Branch No", Text.Trim, type text}, 
      {"Program Name.2", Text.Trim, type text}, 
      {"Client", Text.Trim, type text}, 
      {"Program No", Text.Trim, type text}
    }
  ), 
  #"Cleaned Text" = Table.TransformColumns(
    #"Trimmed Text", 
    {
      {"Insurer  Cat Cd", Text.Clean, type text}, 
      {"MCO Number", Text.Clean, type text}, 
      {"Cat Code", Text.Clean, type text}, 
      {"Geo Region Code", Text.Clean, type text}, 
      {"Claims Made Date", Text.Clean, type text}, 
      {"CP Term Date", Text.Clean, type text}, 
      {"Client Program Status", Text.Clean, type text}, 
      {"Insured  Driver Last Name", Text.Clean, type text}, 
      {"Avg Wkly Wage", Text.Clean, type text}, 
      {"Clmt Job Code", Text.Clean, type text}, 
      {"Clmt Empl No", Text.Clean, type text}, 
      {"Clmt Sex", Text.Clean, type text}, 
      {"Clmt Age", Text.Clean, type text}, 
      {"Juris Days Lost", Text.Clean, type text}, 
      {"Policy Number", Text.Clean, type text}, 
      {"Fed/State Clm No", Text.Clean, type text}, 
      {"Client Clm No", Text.Clean, type text}, 
      {"Adjuster", Text.Clean, type text}, 
      {"Expiration", Text.Clean, type text}, 
      {"Effective", Text.Clean, type text}, 
      {"NCCI Inj Desc", Text.Clean, type text}, 
      {"NCCI Inj Code", Text.Clean, type text}, 
      {"NCCI Class Code", Text.Clean, type text}, 
      {"Location Description", Text.Clean, type text}, 
      {"Location Code", Text.Clean, type text}, 
      {"Level 7 Name", Text.Clean, type text}, 
      {"Level 7 Code", Text.Clean, type text}, 
      {"Level 6 Name", Text.Clean, type text}, 
      {"Level 6 Code", Text.Clean, type text}, 
      {"Level 5 Name", Text.Clean, type text}, 
      {"Level 5 Code", Text.Clean, type text}, 
      {"Level 4 Name", Text.Clean, type text}, 
      {"Level 4 Code", Text.Clean, type text}, 
      {"Level 3 Name", Text.Clean, type text}, 
      {"Level 3 Code", Text.Clean, type text}, 
      {"Level 2 Name", Text.Clean, type text}, 
      {"Level 2 Code", Text.Clean, type text}, 
      {"Recision Date", Text.Clean, type text}, 
      {"Denial Date", Text.Clean, type text}, 
      {"Controverted", Text.Clean, type text}, 
      {"Body Part", Text.Clean, type text}, 
      {"Injury Desc", Text.Clean, type text}, 
      {"Cause Description", Text.Clean, type text}, 
      {"Total Recov", Text.Clean, type text}, 
      {"Legacy Recov", Text.Clean, type text}, 
      {"Non-Legal Recov", Text.Clean, type text}, 
      {"Legal Recov", Text.Clean, type text}, 
      {"Med/BI Recov", Text.Clean, type text}, 
      {"Ind/PD Recov", Text.Clean, type text}, 
      {"Total Inc (Gross)", Text.Clean, type text}, 
      {"Total Outsd", Text.Clean, type text}, 
      {"Total PTD", Text.Clean, type text}, 
      {"Non- Legal Inc", Text.Clean, type text}, 
      {"Non- Legal Outsd", Text.Clean, type text}, 
      {"Non- Legal PTD", Text.Clean, type text}, 
      {"Legal Inc", Text.Clean, type text}, 
      {"Legal Outsd", Text.Clean, type text}, 
      {"Legal PTD", Text.Clean, type text}, 
      {"Med/BI Inc", Text.Clean, type text}, 
      {"Med/BI Outsd", Text.Clean, type text}, 
      {"Med/BI PTD", Text.Clean, type text}, 
      {"Ind/PD Inc", Text.Clean, type text}, 
      {"Ind/PD Outsd", Text.Clean, type text}, 
      {"Ind/PD PTD", Text.Clean, type text}, 
      {"Minor Coverage Description", Text.Clean, type text}, 
      {"Minor Cov Cd", Text.Clean, type text}, 
      {"LOB Code", Text.Clean, type text}, 
      {"Litigation Ind", Text.Clean, type text}, 
      {"Privacy Claim", Text.Clean, type text}, 
      {"Closed/ Reopened Date", Text.Clean, type text}, 
      {"Claim Status Description", Text.Clean, type text}, 
      {"Claim Status Code", Text.Clean, type text}, 
      {"Reported Date", Text.Clean, type text}, 
      {"Loss Date", Text.Clean, type text}, 
      {"Occupation", Text.Clean, type text}, 
      {"Claimant Name", Text.Clean, type text}, 
      {"Premium State", Text.Clean, type text}, 
      {"Garage State", Text.Clean, type text}, 
      {"Benefit State", Text.Clean, type text}, 
      {"Loss State", Text.Clean, type text}, 
      {"Insurer Code", Text.Clean, type text}, 
      {"S/I", Text.Clean, type text}, 
      {"Insurer Name", Text.Clean, type text}, 
      {"Claim Number", Text.Clean, type text}, 
      {"Occurrence Number", Text.Clean, type text}, 
      {"Claim Office", Text.Clean, type text}, 
      {"Branch No", Text.Clean, type text}, 
      {"Program Name.2", Text.Clean, type text}, 
      {"Client", Text.Clean, type text}, 
      {"Program No", Text.Clean, type text}
    }
  ), 
  #"Set Date Types" = Table.TransformColumnTypes(
    #"Cleaned Text", 
    {{"Loss Date", type date}, {"Effective", type date}, {"Expiration", type date}}
  ), 
  #"Full Outer Join with AsOf" = Table.NestedJoin(
    #"Set Date Types", 
    {"Loss Date"}, 
    AsOf, 
    {"Valuation Date"}, 
    "AsOf", 
    JoinKind.FullOuter
  ), 
  #"Expanded AsOf" = Table.ExpandTableColumn(
    #"Full Outer Join with AsOf", 
    "AsOf", 
    {"Valuation Date"}, 
    {"Valuation Date"}
  ), 
  #"Filled Up" = Table.FillUp(#"Expanded AsOf", {"Valuation Date"}), 
  #"Remove rows before AXA XL" = Table.SelectRows(
    #"Filled Up", 
    each [Effective] >= #date(2007, 7, 1)
  ), 
  #"Filtered Rows" = Table.SelectRows(#"Remove rows before AXA XL", each ([LOB Code] = "WC")), 
  #"Renamed Columns" = Table.RenameColumns(
    #"Filtered Rows", 
    {
      {"Total PTD", "Total Paid (Gross)"}, 
      {"Non- Legal Inc", "Non-Legal Inc"}, 
      {"Legacy Recov", "Legacy Recovery"}, 
      {"Non-Legal Recov", "Non-Legal Recovery"}, 
      {"Legal Recov", "Legal Recovery"}, 
      {"Non- Legal PTD", "Non-Legal PTD"}, 
      {"Non- Legal Outsd", "Non-Legal Outsd"}, 
      {"Med/BI Inc", "Medical Incurred (Gross)"}, 
      {"Ind/PD PTD", "Indemnity Paid"}, 
      {"Ind/PD Outsd", "Indemnity O/S"}, 
      {"Ind/PD Inc", "Indemnity Incurred (Gross)"}, 
      {"Med/BI PTD", "Medical Paid"}, 
      {"Med/BI Outsd", "Medical O/S"}, 
      {"Med/BI Recov", "Medical Recovery"}, 
      {"Ind/PD Recov", "Indemnity Recovery"}, 
      {"Loss Date", "Date of Loss"}, 
      {"Insurer Name", "Carrier"}, 
      {"Claimant Name", "Claimant"}, 
      {"Level 2 Code", "Division"}, 
      {"Location Description", "Loc Description"}, 
      {"LOB Code", "LOB"}, 
      {"Claim Status Description", "Claim Status"}, 
      {"Location Code", "Loc Code"}, 
      {"Cause Description", "Claim Description"}
    }
  ), 
  #"Changed Type" = Table.TransformColumnTypes(
    #"Renamed Columns", 
    {
      {"Total Inc (Gross)", Currency.Type}, 
      {"Total Recov", Currency.Type}, 
      {"Total Outsd", Currency.Type}, 
      {"Total Paid (Gross)", Currency.Type}, 
      {"Non-Legal Inc", Currency.Type}, 
      {"Legal Inc", Currency.Type}, 
      {"Non-Legal Recovery", Currency.Type}, 
      {"Legal Recovery", Currency.Type}, 
      {"Non-Legal Outsd", Currency.Type}, 
      {"Legal Outsd", Currency.Type}, 
      {"Non-Legal PTD", Currency.Type}, 
      {"Legal PTD", Currency.Type}, 
      {"Medical Incurred (Gross)", Currency.Type}, 
      {"Medical Recovery", Currency.Type}, 
      {"Medical O/S", Currency.Type}, 
      {"Medical Paid", Currency.Type}, 
      {"Indemnity Incurred (Gross)", Currency.Type}, 
      {"Indemnity Recovery", Currency.Type}, 
      {"Indemnity O/S", Currency.Type}, 
      {"Indemnity Paid", Currency.Type}, 
      {"Effective", type date}, 
      {"Expiration", type date}, 
      {"Date of Loss", type date}
    }
  ), 
  #"Added Custom" = Table.AddColumn(
    #"Changed Type", 
    "Policy Year", 
    each Text.From([Effective]) & "-" & Text.End(Text.From(Date.Year([Expiration])), 2)
  ), 
  #"Add ALAE Paid" = Table.AddColumn(
    #"Added Custom", 
    "ALAE Paid", 
    each [Legal PTD] + [#"Non-Legal PTD"]
  ), 
  #"Add ALAE O/S" = Table.AddColumn(
    #"Add ALAE Paid", 
    "ALAE O/S", 
    each [Legal Outsd] + [#"Non-Legal Outsd"]
  ), 
  #"Add ALAE Recovery" = Table.AddColumn(
    #"Add ALAE O/S", 
    "ALAE Recovery", 
    each [Legal Recovery] + [#"Non-Legal Recovery"]
  ), 
  #"Add Indemnity Incurred" = Table.AddColumn(
    #"Add ALAE Recovery", 
    "Indemnity Incurred", 
    each [Indemnity Paid] + [#"Indemnity O/S"] + [Indemnity Recovery]
  ), 
  #"Add Medical Incurred" = Table.AddColumn(
    #"Add Indemnity Incurred", 
    "Medical Incurred", 
    each [Medical Paid] + [#"Medical O/S"] + [Medical Recovery]
  ), 
  #"Add ALAE Incurred" = Table.AddColumn(
    #"Add Medical Incurred", 
    "ALAE Incurred", 
    each [ALAE Paid] + [#"ALAE O/S"] + [ALAE Recovery]
  ), 
  #"Add Total Paid" = Table.AddColumn(
    #"Add ALAE Incurred", 
    "Total Paid", 
    each [Indemnity Paid] + [Medical Paid] + [ALAE Paid]
  ), 
  #"Add Total O/S" = Table.AddColumn(
    #"Add Total Paid", 
    "Total O/S", 
    each [#"Indemnity O/S"] + [#"Medical O/S"] + [#"ALAE O/S"]
  ), 
  #"Add Total Recovery" = Table.AddColumn(
    #"Add Total O/S", 
    "Total Recovery", 
    each [Indemnity Recovery] + [Medical Recovery] + [ALAE Recovery]
  ), 
  #"Add Net Paid" = Table.AddColumn(
    #"Add Total Recovery", 
    "Net Paid", 
    each [Total Paid] + [Total Recovery]
  ), 
  #"Add Total Incurred" = Table.AddColumn(
    #"Add Net Paid", 
    "Total Incurred", 
    each [Net Paid] + [#"Total O/S"]
  ), 
  #"Add Net Paid (excl. ALAE)" = Table.AddColumn(
    #"Add Total Incurred", 
    "Net Paid (excl. ALAE)", 
    each [Indemnity Paid] + [Indemnity Recovery] + [Medical Paid] + [Medical Recovery]
  ), 
  #"Add Tot Incurred (excl. ALAE)" = Table.AddColumn(
    #"Add Net Paid (excl. ALAE)", 
    "Tot Incurred (excl. ALAE)", 
    each [#"Net Paid (excl. ALAE)"] + [#"Indemnity O/S"] + [#"Medical O/S"]
  ), 
  #"Capitalized Each Word" = Table.TransformColumns(
    #"Add Tot Incurred (excl. ALAE)", 
    {
      {"Claimant", Text.Proper, type text}, 
      {"Division", Text.Proper, type text}, 
      {"Loc Description", Text.Proper, type text}, 
      {"Carrier", Text.Proper, type text}
    }
  ), 
  #"Merged Queries" = Table.NestedJoin(
    #"Capitalized Each Word", 
    {"Effective", "LOB"}, 
    Deductibles, 
    {"Effective", "LOB"}, 
    "Deductibles", 
    JoinKind.LeftOuter
  ), 
  #"Expanded Deductibles" = Table.ExpandTableColumn(
    #"Merged Queries", 
    "Deductibles", 
    {"Deductible"}, 
    {"Deductible"}
  ), 
  #"Add Limited Paid" = Table.AddColumn(
    #"Expanded Deductibles", 
    "Limited Paid", 
    each List.Min({[Net Paid], [Deductible]})
  ), 
  #"Add Limited Incurred" = Table.AddColumn(
    #"Add Limited Paid", 
    "Limited Incurred", 
    each List.Min({[Total Incurred], [Deductible]})
  ), 
  #"Add Limited O/S" = Table.AddColumn(
    #"Add Limited Incurred", 
    "Limited O/S", 
    each [Limited Incurred] - [Limited Paid]
  ), 
  #"Add Excess Paid" = Table.AddColumn(
    #"Add Limited O/S", 
    "Excess Paid", 
    each [Net Paid] - [Limited Paid]
  ), 
  #"Add Excess Incurred" = Table.AddColumn(
    #"Add Excess Paid", 
    "Excess Incurred", 
    each [Total Incurred] - [Limited Incurred]
  ), 
  #"Add Excess O/S" = Table.AddColumn(
    #"Add Excess Incurred", 
    "Excess O/S", 
    each [Excess Incurred] - [Excess Paid]
  ), 
  #"Removed Other Columns" = Table.SelectColumns(
    #"Add Excess O/S", 
    {
      "Claim Number", 
      "Benefit State", 
      "Claimant", 
      "Date of Loss", 
      "Claim Status", 
      "LOB", 
      "Indemnity Paid", 
      "Indemnity O/S", 
      "Medical Paid", 
      "Medical O/S", 
      "Indemnity Recovery", 
      "Medical Recovery", 
      "Claim Description", 
      "Division", 
      "Loc Code", 
      "Loc Description", 
      "Valuation Date", 
      "Policy Year", 
      "ALAE Paid", 
      "ALAE O/S", 
      "ALAE Recovery", 
      "Indemnity Incurred", 
      "Medical Incurred", 
      "ALAE Incurred", 
      "Total Paid", 
      "Total O/S", 
      "Total Recovery", 
      "Net Paid", 
      "Total Incurred", 
      "Net Paid (excl. ALAE)", 
      "Tot Incurred (excl. ALAE)", 
      "Deductible", 
      "Limited Paid", 
      "Limited Incurred", 
      "Limited O/S", 
      "Excess Paid", 
      "Excess Incurred", 
      "Excess O/S"
    }
  ), 
  #"Reordered Columns" = Table.ReorderColumns(
    #"Removed Other Columns", 
    {
      "LOB", 
      "Policy Year", 
      "Claim Number", 
      "Date of Loss", 
      "Claimant", 
      "Benefit State", 
      "Claim Status", 
      "Indemnity Paid", 
      "Indemnity O/S", 
      "Indemnity Recovery", 
      "Indemnity Incurred", 
      "Medical Paid", 
      "Medical O/S", 
      "Medical Recovery", 
      "Medical Incurred", 
      "ALAE Paid", 
      "ALAE O/S", 
      "ALAE Recovery", 
      "ALAE Incurred", 
      "Total Paid", 
      "Total O/S", 
      "Total Recovery", 
      "Net Paid", 
      "Total Incurred", 
      "Net Paid (excl. ALAE)", 
      "Tot Incurred (excl. ALAE)", 
      "Deductible", 
      "Limited Paid", 
      "Limited O/S", 
      "Limited Incurred", 
      "Excess Paid", 
      "Excess O/S", 
      "Excess Incurred", 
      "Division", 
      "Loc Code", 
      "Loc Description", 
      "Claim Description"
    }
  ), 
  #"Sorted Rows" = Table.Sort(#"Reordered Columns", {{"Total Incurred", Order.Descending}})
in
  #"Sorted Rows"
